apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ut-ingress
  namespace: universal-translation
  labels:
    app: universal-translation
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - translate.rxlab.app
      secretName: translate-tls
  rules:
    - host: translate.rxlab.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ut-frontend-service
                port:
                  number: 3000
