apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: universal-translation
  namespace: universal-translation

resources:
  - namespace.yaml
  - configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

namespace: universal-translation

images:
  - name: ghcr.io/rxtech-lab/ut-frontend
    newTag: latest
