apiVersion: v1
kind: Namespace
metadata:
  name: universal-translation
  labels:
    name: universal-translation
    app.kubernetes.io/name: universal-translation
    app.kubernetes.io/managed-by: kustomize
